library verilog;
use verilog.vl_types.all;
entity example_top is
    generic(
        C3_P0_MASK_SIZE : integer := 8;
        C3_P0_DATA_PORT_SIZE: integer := 64;
        C3_P1_MASK_SIZE : integer := 8;
        C3_P1_DATA_PORT_SIZE: integer := 64;
        DEBUG_EN        : integer := 0;
        C3_MEMCLK_PERIOD: integer := 3200;
        C3_CALIB_SOFT_IP: string  := "TRUE";
        C3_SIMULATION   : string  := "FALSE";
        C3_HW_TESTING   : string  := "FALSE";
        C3_RST_ACT_LOW  : integer := 0;
        C3_INPUT_CLK_TYPE: string  := "SINGLE_ENDED";
        C3_MEM_ADDR_ORDER: string  := "ROW_BANK_COLUMN";
        C3_NUM_DQ_PINS  : integer := 16;
        C3_MEM_ADDR_WIDTH: integer := 14;
        C3_MEM_BANKADDR_WIDTH: integer := 3
    );
    port(
        calib_done      : out    vl_logic;
        error           : out    vl_logic;
        mcb3_dram_dq    : inout  vl_logic_vector;
        mcb3_dram_a     : out    vl_logic_vector;
        mcb3_dram_ba    : out    vl_logic_vector;
        mcb3_dram_ras_n : out    vl_logic;
        mcb3_dram_cas_n : out    vl_logic;
        mcb3_dram_we_n  : out    vl_logic;
        mcb3_dram_odt   : out    vl_logic;
        mcb3_dram_reset_n: out    vl_logic;
        mcb3_dram_cke   : out    vl_logic;
        mcb3_dram_dm    : out    vl_logic;
        mcb3_dram_udqs  : inout  vl_logic;
        mcb3_dram_udqs_n: inout  vl_logic;
        mcb3_rzq        : inout  vl_logic;
        mcb3_zio        : inout  vl_logic;
        mcb3_dram_udm   : out    vl_logic;
        c3_sys_clk      : in     vl_logic;
        c3_sys_rst_i    : in     vl_logic;
        mcb3_dram_dqs   : inout  vl_logic;
        mcb3_dram_dqs_n : inout  vl_logic;
        mcb3_dram_ck    : out    vl_logic;
        mcb3_dram_ck_n  : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of C3_P0_MASK_SIZE : constant is 1;
    attribute mti_svvh_generic_type of C3_P0_DATA_PORT_SIZE : constant is 1;
    attribute mti_svvh_generic_type of C3_P1_MASK_SIZE : constant is 1;
    attribute mti_svvh_generic_type of C3_P1_DATA_PORT_SIZE : constant is 1;
    attribute mti_svvh_generic_type of DEBUG_EN : constant is 1;
    attribute mti_svvh_generic_type of C3_MEMCLK_PERIOD : constant is 1;
    attribute mti_svvh_generic_type of C3_CALIB_SOFT_IP : constant is 1;
    attribute mti_svvh_generic_type of C3_SIMULATION : constant is 1;
    attribute mti_svvh_generic_type of C3_HW_TESTING : constant is 1;
    attribute mti_svvh_generic_type of C3_RST_ACT_LOW : constant is 1;
    attribute mti_svvh_generic_type of C3_INPUT_CLK_TYPE : constant is 1;
    attribute mti_svvh_generic_type of C3_MEM_ADDR_ORDER : constant is 1;
    attribute mti_svvh_generic_type of C3_NUM_DQ_PINS : constant is 1;
    attribute mti_svvh_generic_type of C3_MEM_ADDR_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of C3_MEM_BANKADDR_WIDTH : constant is 1;
end example_top;
